// export const GETFOLLOWREQUESTS='GETFOLLOWREQUESTS';
// export const ACCEPTFOLLOW='ACCEPTFOLLOW';
// export const DECLINEFOLLOW='DECLINEFOLLOW';
// export const GETUSERPOSTS='GETUSERPOSTS';
// export const DELETEPOST='DELETEPOST';
// export const LIKEUSERPOST='LIKEUSERPOST';
// export const SETUSERNAME='SETUSERNAME';
// export const GETUSERFOLLOWERSANDFOLLOWING='GETUSERFOLLOWERSANDFOLLOWING';
// export const SEARCHUSERNAME='SEARCHUSERNAME';
// export const UPLOADPOST='UPLOADPOST';
// export const ADDCOMMENT='ADDCOMMENT';
// export const GETCOMMENT='GETCOMMENT';
// export const GETFOLLOWERPOSTS='GETFOLLOWERPOSTS';
// export const NEWDESCRIPTION='NEWDESCRIPTION';
// export const FOLLOWANDUNFOLLOW='FOLLOWANDUNFOLLOW';

export const setUserName=(value) =>{
    return{
        type: "SETUSERNAME",
        payload: value,
      }}